[book]
title = "Pranor Platform Documentation"
authors = ["vyuvaraj"]
language = "en"
src = "."

[build]
build-dir = "_site"

[output.html]
default-theme = "navy"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/vyuvaraj/pranor-platform"
edit-url-template = "https://github.com/vyuvaraj/pranor-platform/edit/main/docs/{path}"
site-url = "/pranor-platform/"

[output.html.search]
enable = true
